[package]
name = "srcr"
version = "0.1.0"
edition = "2021"

[dependencies]
regex="1.11.1"
rayon = "1.10.0"
dotenvy = "0.15.7"
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.42.0", features = ["full"] }
itertools = "0.13.0"